name: open-rdma-driver CI test
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  ci-check:
    name: CI test
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: datenlord/blue-rdma
          ref: next
          fetch-depth: 0
          submodules: 'true'
          path: blue-rdma
      - uses: actions/cache@v4
        id: cache-building-emulator
        with:
          path: |
            ~/.bash_profile
            blue-rdma/bsc-2023.01-ubuntu-22.04
            blue-rdma/test
            ~/.cache/pip
          key: ${{ runner.os }}-blue-rdma-next
      - name: build emulator
        if: steps.cache-building-emulator.outputs.cache-hit != 'true'
        run : |
          cd ./blue-rdma
          ./setup.sh
          ./run_one.sh || true
          pip install scapy 
      - name: run cargo build
        working-directory: rust_driver
        run : cargo build --verbose 
      - name: run cargo test
        working-directory: rust_driver
        run : cargo test --verbose -- --skip test_loopback_software_device # currently skip because of permission denied
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3